# Generated by Django 4.0.4 on 2022-09-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensturation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='period',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='period',
            name='heart_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='period',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='period',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='period',
            name='average_body_temp_per_day',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='period',
            name='average_calories_burnt_per_day',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='period',
            name='average_heart_rate_per_day',
            field=models.FloatField(default=0),
        ),
    ]
